[project]
name = "image2biomass"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "timm>=1.0.22",
    "torch>=2.9.1",
]
